### ISSUE TITLE
How to launch from Ubuntu 14.04?

### ISSUE THREAD

**Issue by ghost** [RigsOfRods/ror-linux-buildscripts#4]
I ran the scripts in order on Ubuntu on my Linux partition, but I cannot find how to launch it. I saw a rigs of rods folder in the Home directory but no apparent way to launch it.

**Comment by Hiradur** [comment]
```
cd ~/rigs-of-rods/install/bin
./RoR
```

in Terminal or just double click the RoR icon in that folder

**Comment by ghost** [comment]
That directory does not exist. 

```
 On Monday, July 6, 2015 11:27 PM, Hiradur <notifications@github.com> wrote:
```

 cd ~/rigs-of-rods/install/bin
./RoR
in Terminal or just double click the RoR icon in that folder—

**Comment by Hiradur** [comment]
It has to exist if you didn't change anything in the config file coming with the scripts. Did you forget the ~ character perhaps (which is a shortcut to your home directory)?

If that doesn't work then open the rigs-of-rods folder you saw in your home directory, then open install, then bin and there should be RoR and RoRConfig which you can start by double clicking them.

**Comment by Hiradur** [comment]
Problem solved?

**Comment by ghost** [comment]
No. :(

**Comment by Hiradur** [comment]
Unless you changed the paths in `config` ~/rigs-of-rods has to exist or something beyond the reach of the script went very wrong. It's either that or you simply didn't run all 3 scripts in a row. Are you sure you followed the steps stated in Readme.md correctly?

**Comment by ghost** [comment]
Yes I did.

**Comment by Hiradur** [comment]
This is weird. Could you run all scripts again to see if this fixes the issue? Watch out for error messages in the console (the script should stop when an error occurs).

**Comment by ghost** [comment]
The only folder in rigs-of-rods is source.
Here's a terminal session recorded of me typing the commands and the output: I think it contains all the error messages I encountered:
http://69.107.93.145/Uploads/output.txt

**Comment by ghost** [comment]
Maybe the terminal output during installation would help.

**Comment by Hiradur** [comment]
There was an error when running RoRdeps.sh:

``` shell
[ 61%] Built target Plugin_ParticleFX
make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libGL.so', needed by `lib/RenderSystem_GL.so.1.8.2'.  Stop.
make[1]: *** [RenderSystems/GL/CMakeFiles/RenderSystem_GL.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 64%] Built target OgrePaging
[ 65%] [ 69%] Built target OgreProperty
Built target Plugin_PCZSceneManager
make: *** [all] Error 2
```

I don't really know how that happened. Can you tell me your system specs?

PS: If a script stops with an error it doesn't make sense to run the other scripts.

**Comment by ghost** [comment]
Intel Core i5-4440 (Quad-core, 3.1 GHz), 8 GB DDR3-1600 RAM, Nvidia GeForce GTX 750 Ti Superclocked. I did install the graphics drivers in Linux.

**Comment by ShannonVanWagner** [comment]
Something I noticed in your log, probably unrelated because all the dependencies seem to show as installed, but can clean up anyway..

---

W: Failed to fetch https://launchpad.net/~aapo-rantalainen/+archive/ror-038-stable/dists/trusty/main/binary-amd64/Packages  HttpError404
...
W: Failed to fetch https://launchpad.net/~aapo-rantalainen/+archive/ror-038-stable/dists/trusty/main/binary-i386/Packages  HttpError404
...
E: Some index files failed to download. They have been ignored, or old ones used instead.
...
 0 upgraded, 0 newly installed, 0 to remove and 324 not upgraded.

---

Appears you might have tried installing RoR from aapo-rantalainen's PPA there.. Probably this wouldn't prevent custom-building RoR per the scripts from this repo, but I'd clean it off anyway if it were me. Also, perhaps updating your system might help per the last line there..

I'd try uninstalling the PPA per https://launchpad.net/~aapo-rantalainen/+archive/ubuntu/ror-038-stable:
sudo add-apt-repository --remove ppa:aapo-rantalainen/ror-038-stable
sudo apt-get remove rigsofrods
sudo apt-get autoremove

Then I'd upgrade my system:
sudo apt-get update && sudo apt-get upgrade (then confirm with y, after ensuring "remove" doesn't have anything important - e.g., ubuntu-desktop)

**Comment by ghost** [comment]
I'll do that next time I boot into Linux, thanks!

**Comment by ghost** [comment]
When I upgrade my system, it says that some index files failed to download. What do I do now?

**Comment by ShannonVanWagner** [comment]
It's probably failing on the sudo add-apt-repository --remove command there because that URL appearing in your sources is invalid. Seems like it would have been an older version of the PPA because the current one doesn't cause the same issue.

There's probably a broken url that contained in a file like this on your computer from the ppa:
/etc/apt/sources.list.d/aapo-*

For example, this is the broken URL (gets page not found on launchpad site):
https://launchpad.net/~aapo-rantalainen/+archive/ror-038-stable/dists/trusty/main/binary-i386/Packages 

Maybe if you could provide the output from these command, I could help you further:
$ ls /etc/apt.sources.list.d/aapo-*
$ cat /etc/apt.sources.list.d/aapo-*

At this point, if it were me, I'd just disable the PPA sources by commenting them out, then get update the system updates completed. Probably that broken URL is blocking the rest of your system updates. Again, the system updates may not have any bearing on using the scripts in this repository at all. That said, with that many updates due for the system, there are probably some important security fixes waiting to be applied.

Another question I'd have, is whether you followed the instructions before at the PPA website? If so, we'd need to see if that's conflicting with your current build from this repo at all.
https://launchpad.net/~aapo-rantalainen/+archive/ubuntu/ror-038-stable 

For example, I notice that PPA has you create a .rigsofrods directory and then copy stuff from /opt/rigsofrods into it... Seems like you'd probably want to do some cleanup on that stuff before trying to use the scripts in this repository. If nothing else, could rename ~/.rigsofrods so as to avoid any conflict.

Also, I noticed something in the log from my building/installing from the scripts in this repository: There's a line that says:
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so 
I don't see that same line in the output.txt that you posted, which may explain why the 'make' fails when looking for the related file.

Further inspection of the above file on my system shows it's actually a symlink that points to other location:
1.) $ ls -l /usr/lib/x86_64-linux-gnu/libGL.so
lrwxrwxrwx 1 root root 13 Jul 27 02:17 /usr/lib/x86_64-linux-gnu/libGL.so -> mesa/libGL.so

If you run the command in #1, do you get the same (or similar) result as above? If you get 'No such file or directory' instead of the result above, then either the symlink doesn't exist, or the symlink and mesa/libGL.so files don't exist. 

2.) You can test for the existence of  /usr/lib/x86_64-linux-gnu/mesa/libGL.so with this command (and there should be a similar output):
$ ls -l /usr/lib/x86_64-linux-gnu/mesa/libGL.so
lrwxrwxrwx 1 root root 14 Jul 27 02:17 /usr/lib/x86_64-linux-gnu/mesa/libGL.so -> libGL.so.1.2.0

If you get a similar output to #2 above, but not for #!, then you might be able to easily fix the problem by creating the symlink with these commands:
cd /usr/lib/x86_64-linux-gnu
sudo ln -s mesa/libGL.so /usr/lib/x86_64-linux-gnu/libGL.so

**Comment by Hiradur** [comment]
Closing this as this seems to be an issue with the underlying setup, not the scripts themselves.
Feel free to reopen if you disagree.

**Comment by pcwizzy37** [comment]
I built RoR, and it is extremely buggy, doesn't render correctly, cars go bazerk like Jello, or Marv from home Alone 2 when He was shocked.
